twitch_client_id = "123456789101112131415"
twitch_client_secret = "123456789101112131415"
priority_streamers = [
	"bfroggio",
	"fullfledgedlad",
	"breadycorn",
	"odinZAte"
]
backup_streamers = [
	"pappadopolis84",
	"malic_vr",
	"RocketLeague"
]
games_blacklist = [
	"The Evil Within",
	"Resident Evil",
	"Dead Space"
]
